# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 462931888b09cd6fdce8abab6069f2ae04c136f1253628cfdf9b896b46b394db91f50735d92140545def0bf3013843614e178eb2257b9b4c0d8e3055f9b34ad3

test:
  secret_key_base: a21059a14a93848ba78842482e8ddb523c2fcf9c3527a8dd82510fe7b6d7278ea17d3616b7cbd015eb956f8a1b17b5d5ec3e6d3df22c52edf524eee3611015e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
